name: projects
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.10
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0  # Moved this inside dev_dependencies

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: font/Montserrat-Regular.ttf

  assets:
    - assets/dice1.jpg
    - assets/dice2.jpg
    - assets/dice3.jpg
    - assets/dice4.jpg
    - assets/dice5.jpg
    - assets/dice6.jpg
